language: node_js
node_js:
    - '8.9.3'

install:
  - npm install

before_script:
  - npm test

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github-token: 62f61e5f6c652786ae8308858bdf9e382d573794
  local_dir: build
  email: shye0000@gmail.com
  on:
    branch: master