language: node_js
node_js:
    - '8.9.3'

install:
  - npm install

before_script:
  - npm test

script:
  - git config --global user.email shye0000@gmail.com
  - npm run deploy

branches:
  only:
    - master