language: node_js
node_js:
    - '8.9.3'

install:
  - npm install

before_script:
  - npm run test:coverage

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  email: shye0000@gmail.com
  on:
    branch: master
