language: node_js
node_js:
    - '8.9.3'

install:
  - npm install

before_script:
  - npm test

script:
  - npm run deploy

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure_token: 508b156b49712b4ea6e41d3a02a35f7cf24fa779